USE catalog_cafe;

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Chaika',
     'Chaika approach - comfort food for every day:  the menu would be both satisfying and interesting',
     'Greek and Mediterranean cuisines are well prepared in Chayka. Go and enjoy a fascinating polenta in this place if you are not far away. Delicious yogurt is the tastiest dish. The wine list is impressive, it will delight all palates. Some visitors like great tea at this place. Huge service is always a pleasure. Most of the time, this cafe provides you with an exotic atmosphere.',
     'Kyiv',
     'Baseina St, 5Б, Kyiv, 01004',
     '10.00 - 21.00',
     '$$',
     50,
     'Middle',
     15,
     NULL,
     NULL,
     1,
     0,
     0,
     NULL,
     'https://www.instagram.com/chayka.kyiv/',
     'https://www.facebook.com/chayka.kyiv/',
     'https://chayka.choiceqr.com/',
     'https://images2.imgbox.com/20/b5/WTQTMlhN_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('City Zen Café',
     'The menu includes the hits of modern urban cuisine: breakfasts, salads, burgers, smoothies, coffee, desserts and much more.',
     'City-Zen is a place where you can forget about the hustle and bustle and find harmony within yourself. It is cozy here both alone and in the company of relatives and friends. The secret of the attractiveness of our institutions is their versatility combined with a friendly character and lack of pathos.',
     'Kyiv',
     'Rusanivska Embankment, 10, Kyiv, 02154',
     '09.00 - 20.00',
     '$$',
     250,
     'Middle',
     25,
     NULL,
     NULL,
     1,
     1,
     0,
     NULL,
     'https://www.facebook.com/cafe.cityzen/',
     'https://www.facebook.com/cafe.cityzen/',
     'www.cityzen.com.ua',
     'https://thumbs2.imgbox.com/3d/97/Do0PbS3F_t.png');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Coffee Lover ',
     'Coffee Lover is a modern roastery, coffee shop and event space',
     'We have been roasting and shipping coffee to coffee shops, restaurants and offices throughout Ukraine for 6 years.
     We are a modern coffee production in Kyiv [VDNG, Pavilion No. 15]
     The menu offers a wide selection of breakfasts, sandwiches, and salads. The drinks menu includes: classic and alternative coffee, teas, lemonades, cocktails and wine.',
     'Kyiv',
     'Akademika Hlushkova Ave, 1П15, Kyiv, 02000',
     '08.00 - 20.00',
     '$$',
     150,
     'Middle',
     20,
     NULL,
     NULL,
     1,
     1,
     1,
     NULL,
     'https://www.instagram.com/coffee_lover_ua/?hl=en',
     'https://www.facebook.com/coffeeloverkyiv/',
     'https://coffeelover.com.ua/',
     'https://images2.imgbox.com/5e/f7/jsiRPwrI_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Druzi',
     'DRUZI City Cafe & Bar is a cozy nest that always welcomes the visits of our dear guests. An ideal place for meeting true friends.',
     'Thinking through the concept of the cafe, the owners tried to create a cozy friendly atmosphere in it and make the menu understandable for both Ukrainians and visitors. Druzi Cafe prepares "international sandwiches", Ukrainian borscht, and serves alcoholic drinks of its own production. The main focus of the menu is on sandwiches, burgers and pizza.',
     'Kyiv',
     'Andriivs''kyi descent, 2Д, Kyiv, 04070',
     '09.00 - 23.00',
     '$$',150,
     'Low',30,NULL,NULL,
     1,
     1,
     0,NULL,
     'https://www.instagram.com/druzicafe/',
     'https://www.facebook.com/Druzicafe/',
     'https://druzicafe-podil.choiceqr.com/',
     'https://thumbs2.imgbox.com/e9/7e/SKqnU9cP_t.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Dubler',
     'A cafe is for every day in Pechersk',
     'A cafe is for every day in Pechersk where you can have breakfast and drink coffee, have lunch, or stop by for a glass of wine on your way home from work in the evening.',
     'Kyiv',
     'Ioanna Pavla II St, 10/1, Kyiv, 01042',
     '09.00 - 21.00',
     '$$$',250,
     'Low',15,NULL,NULL,
     1,
     1,
     0,NULL,
     'https://www.instagram.com/dubler.cafe/',
     'https://www.facebook.com/dubler.cafe/',NULL,
     'https://images2.imgbox.com/6f/25/JdjUufm3_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Faina Familia',
     'Cuisine of delicious Europe',
     'With us, you can have a great breakfast with your family, go for a work lunch in the afternoon, and meet friends or a loved one in the evening. And of course, to celebrate a birthday, engagement or wedding! In a world full of copies, we are "handmade" and a project born out of great love for work and guests!',
     'Kyiv',
     'Verkhnii Val St, 10, Kyiv, 04071',
     '11.00 - 21.00',
     '$$',200,
     'Low',20,NULL,NULL,
     1,
     1,
     0,NULL,
     'https://www.instagram.com/fine_family_/',
     'https://www.facebook.com/finefamily',
     'www.finefamily.com.ua',
     'https://thumbs2.imgbox.com/8a/03/wLdNbYWK_t.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('First Point',
     'Cofee place in the heart of Podil',
     'First Point Cafe is a quirky, tourist-themed place that serves the best coffee in Kyiv. Each visitor will be able to have a great time in a pleasant company. Here you can take an individual barista course, learn the specifics of preparing each type of coffee, purchase natural products and high-quality accessories.',
     'Kyiv',
     'Yaroslavska str 14/20',
     '09.00 - 20.00',
     '$',100,
     'Low',7,NULL,NULL,
     1,
     0,
     0,NULL,
     'https://www.instagram.com/firstpointcoffee/?hl=en',
     'https://www.facebook.com/firstpointcoffee/?paipv=0&eav=AfZh6bvortd5IzT2D2M7plHDNvFWWeDwRRjQsAMAqcZg-fogJG6MKvvtCq_P234ojNs&_rdr',
     'https://firstpoint.coffee/',
     'https://images2.imgbox.com/1f/e1/W28TnAJq_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Ganter Coffee',
     'Harmonic coffee place for your joy and inspiration.',
     ' If hungry, come here for good pies. It''s a must when visiting Ganter to try delicious coffee. The cosy atmosphere of this place makes customers feel relaxed and have a nice time. The accommodating barista welcomes guests all year round.',
     'Kyiv',
     'Laboratorna St, 28, Kyiv, 03150',
     '8.00-21.00',
     '$',120,
     'Middle',10,NULL,NULL,
     1,
     0,
     0,NULL,
     'https://www.instagram.com/ganter_coffee/',
     'https://www.facebook.com/GanterCoffee/',NULL,
     'https://images2.imgbox.com/d3/14/kNKt0nX8_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Home Café',
     'Cozy restaurant with a pleasant atmosphere and delicious food',
     'Home Cafe is a cozy restaurant with a pleasant atmosphere and delicious food. The restaurant''s menu consists of homemade cuisine, and all desserts are made in its own confectionery. An excellent place for lunch or dinner with family and friends, friendly gatherings over a cup of coffee and delicious cakes.',
     'Kyiv',
     'Predslavynska St, буд.55, Kyiv, 03150',
     '09.00 - 21.00',
     '$',400,
     'Low',30,NULL,NULL,
     1,
     1,
     1,NULL,
     'https://www.instagram.com/homecafekiev/?hl=en',
     'https://www.facebook.com/HomeCafe1/',
     'https://www.homecafe.com.ua/',
     'https://images2.imgbox.com/54/cc/5Gjs9Mcb_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Honey ',
     'Casual option known for creative desserts, eclairs & macaroons, plus breakfast staples & light fare.',
     'Honey cafe concept is the author''s confectionery, which is based on the masterpieces of the classical French school and family cafe with original kitchen, which supports pastry shop theme. Owner of the storefront set a task to create bright and comfortable interior, the main advantage of which should be the products located in the largest confectionery shop window in Kiev city. Confectionery interior made in the original style, combining a slight hint of bohemianism of old European confectionery and some eccentricity, already traditional for modern interiors. Plenty of natural light entering into the room, plenty of indoor plants, natural wood, pleasant textiles and bright surfaces in the interior provide atmosphere and comfort.',
     'Kyiv',
     'Yaroslaviv Val St, 20, Kyiv, Ukraine, 01030',
     '08.00 - 21.30',
     '$$',300,
     'Low',20,NULL,NULL,
     1,
     1,
     0,NULL,
     'https://www.instagram.com/honey_cafe/',
     'https://www.facebook.com/honeycafe.com.ua',
     'https://honeycafe.choiceqr.com/menu',
     'https://images2.imgbox.com/a5/84/qGcCva0P_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Idealist Coffee Co',
     'Coffee shop with full menu and special coffee line located in the historical building near the Pecherska subway station',
     'The cafe is located in the historical building of the medieval bastion. In the coffee shop, they state that they want to make delicious coffee available to every Ukrainian. Therefore, on the shelves of the new Idealist, you can buy coffee both in drips and in beans. The cafe also has a full menu with pastries, breakfasts and main dishes.',
     'Kyiv',
     'Yevhena Konovaltsia St, 44, Kyiv, 02000',
     '08.00 - 21.00',
     '$$',200,
     'Middle',25,NULL,NULL,
     1,
     1,
     1,NULL,
     'https://instagram.com/idealistcoffee/',
     'https://facebook.com/iamidealistcoffeeco/',
     'https://idealistcoffee9.choiceqr.com/',
     'https://images2.imgbox.com/87/81/SEiMPKsj_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Mon Cher',
     'Restaurant of Ukrainian and Lebanese cuisine',
     'Talented chefs will surprise you not only with traditional Ukrainian and delicious European dishes, but also with exotic Lebanese dishes. Everything is very simple, tasty and at the same time very healthy. Not only food, but also the wine list of the restaurant will delight true connoisseurs of wine.',
     'Kyiv',
     'Zhylianska St, 124, Kyiv, 02000',
     '10.00 - 22.00',
     '$',150,
     'Low',15,NULL,NULL,
     1,
     1,
     0,NULL,NULL,NULL,
     'moncher.in.ua',
     'https://images2.imgbox.com/70/42/jfro0vRk_o.png');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('ONE LOVE espresso bar',
     'The ONE LOVE espresso bar is a great, affordable and very beautiful place. Suitable for meetings, dates, lunch break.',
     'ONE LOVE espresso bar is a bar, the geometric interior of the coffee place organically merged into the general view of the business center "Toronto-Kyiv" (location of the espresso bar). And now not only local office workers can finally admire the bewitching view of the St. Nicholas Church, but you too - sitting on the terrace with a cup of branded coffee.',
     'Kyiv',
     'Velyka Vasylkivska St, 100, Kyiv, 03150',
     '09.00 - 20.00',
     '$$',200,
     'Low',30,NULL,NULL,
     1,
     1,
     1,NULL,
     'https://www.instagram.com/oneloveespressobar/',
     'https://www.facebook.com/onelovecoffeeua/',
     'https://oneloveespressobar.choiceqr.com/',
     'https://thumbs2.imgbox.com/d8/ea/6G6MdGrh_t.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Pesto Café',
     'Cozy restaurant delights both adults and children every day.There is a lot of light, greenery, flowers and life.',
     'The most important thing for us is to create convenience and comfort for the family, we pay special attention to children! For us, family is a place where you are always waiting, where you are always happy to see and you feel comfortable and convenient. All PESTO CAFEs are equipped with separate children''s rooms, where little guests can play with their favorite toys, watch cartoons, draw, jump, and have fun just like at home. All children''s rooms work with a nanny.',
     'Kyiv',
     'Lobanovskyi Ave, 4д, Kyiv, 02000',
     '10.00 - 22.00',
     '$$',200,
     'High',18,NULL,NULL,
     0,
     1,
     0,NULL,
     'https://www.instagram.com/pesto.cafe/?hl=en',
     'https://www.facebook.com/pestocafe.kiev/',
     'www.pesto-family.com',
     'https://images2.imgbox.com/9d/53/1yXAqfKz_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Positano',
     'True Napoli cuisine on the left bank of Dnipro river',
     'Positano, a Kyiv restaurant of Neapolitan cuisine, took 30th place in the ranking of the best pizzerias in the world by the 50 Top Pizza guide. This is the only Ukrainian institution included in the list. The restaurant''s kitchen is headed by the brand-chef of the "Silpo" chain, Marco Cervetti. The basis of the menu was created by Marco together with pizzaiolo Enzo Coccia. Kyiv restaurant of Neapolitan cuisine Positano took 30th place in the rating of the best pizzerias in the world by the 50 Top Pizza guide. This is the only Ukrainian institution included in the list. The restaurant''s kitchen is headed by the brand-chef of the "Silpo" chain, Marco Cervetti. The basis of the menu was created by Marco together with pizzaiolo Enzo Coccia.',
     'Kyiv',
     'Pavla Tychyny Ave, 1в, Kyiv, 02000',
     '11.00 - 22.00',
     '$$',150,
     'High',40,NULL,NULL,
     1,
     1,
     1,NULL,
     'https://www.instagram.com/positano.ua/?fbclid=IwAR1dxWUJnIxQVTr-unVxrYWgmw08ymltz0Ts_yPgWoVUFYgeTSuYhHSiluk',
     'https://www.facebook.com/PositanoPizzeriaKiev/?fref=ts',
     'https://positano.kiev.ua/',
     'https://images2.imgbox.com/44/32/2dNtqZ6z_o.png');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Shalom',
     'Café with modern Israel cuisine',
     'This is an institution for every day. This is a story without pathos and super prices, with clear, high-quality and tasty food',
     'Kyiv',
     'Ivana Mazepy St, 5, Kyiv, 02000',
     '08.00 - 22.00',
     '$$',100,
     'Middle',40,NULL,NULL,
     1,
     1,
     0,NULL,
     'https://www.instagram.com/shalom.ukraine/?hl=en',
     'https://www.facebook.com/Shalom.Ukraine/',
     'https://shalom.choiceqr.com/menu',
     'https://images2.imgbox.com/85/0f/OAEQUaBV_o.png');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Smartass Kitchen & Bar',
     'The main idea of the restaurant is delicious food without the use of sugar and refined products',
     'The restaurant is part of the Smartass establishment. The complex has a sports club, a beauty area, a restaurant and a bar. The menu includes: breakfasts, soups, snacks, salads, main dishes and desserts. Drinks include coffee, tea, alcohol.',
     'Kyiv',
     'Zhylianska St, 41А, Kyiv, Ukraine, 02000',
     '08.00 - 21.00',
     '$$$',400,
     'Middle',15,NULL,NULL,
     1,
     1,
     1,NULL,
     'https://www.instagram.com/smartass_kitchenandbar/',
     'https://www.facebook.com/SmartassClubUkraine/',
     'https://smartasskitchen.choiceqr.com/',
     'https://images2.imgbox.com/f7/60/jeCsrKoO_o.png');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Soul Café',
     'All-day breakfast, salads, and sandwiches in a cozy space',
     'The legendary city cafe on Rusanivka with breakfasts all day and a friendly team. A good menu of dishes, quality coffee, non-market wines and original cocktails. We have our own Soul catering and will soon open our own Soul bakery.',
     'Kyiv',
     'Rusanivska Embankment, 10, Kyiv, 02000',
     '08.00 - 21.00',
     '$$',200,
     'Low',15,NULL,NULL,
     1,
     1,
     0,NULL,
     'https://www.instagram.com/soulcafe10/',
     'https://www.facebook.com/soulcafe10',
     'http://soul-menu.tilda.ws/',
     'https://images2.imgbox.com/54/c5/ooYvb09a_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Stories Café',
     'Family cafe with an incredible atmosphere for a pleasant and quiet rest',
     'Here you can have a great evening in the company of friends with appetizer sets, Bavarian sausages and bruschettas, and return again the next day for breakfast. After all, they are tasty and healthy here, especially with fruit juices.',
     'Kyiv',
     'Kostiantynivska St, 20/14, Kyiv, 04071',
     '10.00 - 21.00',
     '$$',150,
     'Low',20,NULL,NULL,
     1,
     1,
     1,NULL,
     'https://.instagram.com/storiescafe.ua/?hl=en',
     'https://.facebook.com/storiescafe.ua/',
     'https://stories.choiceqr.com/',
     'https://images2.imgbox.com/d2/cb/cs87LDZR_o.jpeg');

INSERT INTO `catalog_cafe`.`cafes`
(`name`,
 `short_description`,
 `description`,
 `city`,
 `address`,
 `hours`,
 `price_level`,
 `min_order`,
 `noise_level`,
 `tables_number`,
 `latitude`,
 `longitude`,
 `vegan_option`,
 `alcohol`,
 `event_room`,
 `rating`,
 `instagram_link`,
 `facebook_link`,
 `website_link`,
 `logo_link`)
VALUES
    ('Very Well Café',
     'Very Well Café is a spacious and homely place. The main principle of our chef is to cook deliciously, simply, and in a family way. ',
     'Very Well Café is a spacious and homely place. The main principle of our chef is to cook deliciously, simply, and in a family way. But at the same time, 50% of Very Well Cafe''s kitchens have Italian notes. You will not be indifferent to grilled meat, hot dishes, and salads. And you will especially remember the sweet taste of signature desserts, so don''t forget to try Napoleon, which has been the hallmark of the establishment, as our guests have independently declared, for many years. We invite you to visit our family, homely, cozy place.',
     'Kyiv',
     'Aviakonstructor Igor Sikorsky St, 1а, Kyiv, 04112',
     '7am - 10pm',
     '$$',100,
     'Middle',20,NULL,NULL,
     1,
     1,
     0,NULL,
     'https://instagram.com/verywellcafe/',
     'https://facebook.com/VeryWellCafe',
     'www.verywellcafe-sk.choiceqr.com',
     'https://images2.imgbox.com/c9/5c/0KqL3Zkd_o.jpeg');